import os
import time

for i in xrange(165):
    #copy test case i from \cases directory to the current directory, this overwrites previously copies input file
    os.system('copy /Y .\cases\input{0}.txt .\input.txt'.format(i))
    
    print("-->On test case #{0}<--".format(i))
    start_time = time.time()
    
    # Run the script on the input copied above
    os.system('python path_finding.py')
    
    # Display the actual run time
    print("Runing time: {0}ms".format(int((time.time() - start_time) * 1000)))
    
    # Compare the output generated by the script and the correct output in \cases directory
    os.system('FC .\output.txt .\cases\output{0}.txt'.format(i))
    
    # Move your output file to \cases directory
    os.system('copy /Y .\output.txt .\cases\Your_output{0}.txt'.format(i))
